/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallpapersRouteImport } from './routes/wallpapers'
import { Route as SummerCampRouteImport } from './routes/summer-camp'
import { Route as SoulSyncRouteImport } from './routes/soul-sync'
import { Route as SfzRouteImport } from './routes/sfz'
import { Route as SereneMindRouteImport } from './routes/serene-mind'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestSfzRouteImport } from './routes/request-sfz'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as OnenessYogaRouteImport } from './routes/oneness-yoga'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AllUpcomingSfzEventsRouteImport } from './routes/allUpcoming-sfz-events'
import { Route as AllPastSfzEventsRouteImport } from './routes/allPast-sfz-events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSubmitRouteImport } from './routes/blog.submit'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as AdminTrainersRouteImport } from './routes/admin.trainers'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSiteMediaRouteImport } from './routes/admin.site-media'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminEventsIdRouteImport } from './routes/admin.events.$id'

const WallpapersRoute = WallpapersRouteImport.update({
  id: '/wallpapers',
  path: '/wallpapers',
  getParentRoute: () => rootRouteImport,
} as any)
const SummerCampRoute = SummerCampRouteImport.update({
  id: '/summer-camp',
  path: '/summer-camp',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulSyncRoute = SoulSyncRouteImport.update({
  id: '/soul-sync',
  path: '/soul-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SfzRoute = SfzRouteImport.update({
  id: '/sfz',
  path: '/sfz',
  getParentRoute: () => rootRouteImport,
} as any)
const SereneMindRoute = SereneMindRouteImport.update({
  id: '/serene-mind',
  path: '/serene-mind',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestSfzRoute = RequestSfzRouteImport.update({
  id: '/request-sfz',
  path: '/request-sfz',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OnenessYogaRoute = OnenessYogaRouteImport.update({
  id: '/oneness-yoga',
  path: '/oneness-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AllUpcomingSfzEventsRoute = AllUpcomingSfzEventsRouteImport.update({
  id: '/allUpcoming-sfz-events',
  path: '/allUpcoming-sfz-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AllPastSfzEventsRoute = AllPastSfzEventsRouteImport.update({
  id: '/allPast-sfz-events',
  path: '/allPast-sfz-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSubmitRoute = BlogSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => BlogRoute,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const AdminTrainersRoute = AdminTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteMediaRoute = AdminSiteMediaRouteImport.update({
  id: '/site-media',
  path: '/site-media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/allPast-sfz-events': typeof AllPastSfzEventsRoute
  '/allUpcoming-sfz-events': typeof AllUpcomingSfzEventsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/oneness-yoga': typeof OnenessYogaRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/request-sfz': typeof RequestSfzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/serene-mind': typeof SereneMindRoute
  '/sfz': typeof SfzRoute
  '/soul-sync': typeof SoulSyncRoute
  '/summer-camp': typeof SummerCampRoute
  '/wallpapers': typeof WallpapersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/site-media': typeof AdminSiteMediaRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/submit': typeof BlogSubmitRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/allPast-sfz-events': typeof AllPastSfzEventsRoute
  '/allUpcoming-sfz-events': typeof AllUpcomingSfzEventsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/oneness-yoga': typeof OnenessYogaRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/request-sfz': typeof RequestSfzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/serene-mind': typeof SereneMindRoute
  '/sfz': typeof SfzRoute
  '/soul-sync': typeof SoulSyncRoute
  '/summer-camp': typeof SummerCampRoute
  '/wallpapers': typeof WallpapersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/site-media': typeof AdminSiteMediaRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/submit': typeof BlogSubmitRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/allPast-sfz-events': typeof AllPastSfzEventsRoute
  '/allUpcoming-sfz-events': typeof AllUpcomingSfzEventsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/oneness-yoga': typeof OnenessYogaRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/request-sfz': typeof RequestSfzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/serene-mind': typeof SereneMindRoute
  '/sfz': typeof SfzRoute
  '/soul-sync': typeof SoulSyncRoute
  '/summer-camp': typeof SummerCampRoute
  '/wallpapers': typeof WallpapersRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/site-media': typeof AdminSiteMediaRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/submit': typeof BlogSubmitRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/account'
    | '/admin'
    | '/allPast-sfz-events'
    | '/allUpcoming-sfz-events'
    | '/blog'
    | '/contact-us'
    | '/forgot-password'
    | '/gallery'
    | '/get-involved'
    | '/login'
    | '/oneness-yoga'
    | '/programs'
    | '/register'
    | '/request-sfz'
    | '/reset-password'
    | '/serene-mind'
    | '/sfz'
    | '/soul-sync'
    | '/summer-camp'
    | '/wallpapers'
    | '/admin/gallery'
    | '/admin/site-media'
    | '/admin/testimonials'
    | '/admin/trainers'
    | '/blog/$id'
    | '/blog/submit'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/blog/'
    | '/admin/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/account'
    | '/admin'
    | '/allPast-sfz-events'
    | '/allUpcoming-sfz-events'
    | '/blog'
    | '/contact-us'
    | '/forgot-password'
    | '/gallery'
    | '/get-involved'
    | '/login'
    | '/oneness-yoga'
    | '/programs'
    | '/register'
    | '/request-sfz'
    | '/reset-password'
    | '/serene-mind'
    | '/sfz'
    | '/soul-sync'
    | '/summer-camp'
    | '/wallpapers'
    | '/admin/gallery'
    | '/admin/site-media'
    | '/admin/testimonials'
    | '/admin/trainers'
    | '/blog/$id'
    | '/blog/submit'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/blog'
    | '/admin/events'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/account'
    | '/admin'
    | '/allPast-sfz-events'
    | '/allUpcoming-sfz-events'
    | '/blog'
    | '/contact-us'
    | '/forgot-password'
    | '/gallery'
    | '/get-involved'
    | '/login'
    | '/oneness-yoga'
    | '/programs'
    | '/register'
    | '/request-sfz'
    | '/reset-password'
    | '/serene-mind'
    | '/sfz'
    | '/soul-sync'
    | '/summer-camp'
    | '/wallpapers'
    | '/admin/gallery'
    | '/admin/site-media'
    | '/admin/testimonials'
    | '/admin/trainers'
    | '/blog/$id'
    | '/blog/submit'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/blog/'
    | '/admin/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AllPastSfzEventsRoute: typeof AllPastSfzEventsRoute
  AllUpcomingSfzEventsRoute: typeof AllUpcomingSfzEventsRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactUsRoute: typeof ContactUsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  LoginRoute: typeof LoginRoute
  OnenessYogaRoute: typeof OnenessYogaRoute
  ProgramsRoute: typeof ProgramsRoute
  RegisterRoute: typeof RegisterRoute
  RequestSfzRoute: typeof RequestSfzRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SereneMindRoute: typeof SereneMindRoute
  SfzRoute: typeof SfzRoute
  SoulSyncRoute: typeof SoulSyncRoute
  SummerCampRoute: typeof SummerCampRoute
  WallpapersRoute: typeof WallpapersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallpapers': {
      id: '/wallpapers'
      path: '/wallpapers'
      fullPath: '/wallpapers'
      preLoaderRoute: typeof WallpapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summer-camp': {
      id: '/summer-camp'
      path: '/summer-camp'
      fullPath: '/summer-camp'
      preLoaderRoute: typeof SummerCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul-sync': {
      id: '/soul-sync'
      path: '/soul-sync'
      fullPath: '/soul-sync'
      preLoaderRoute: typeof SoulSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sfz': {
      id: '/sfz'
      path: '/sfz'
      fullPath: '/sfz'
      preLoaderRoute: typeof SfzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serene-mind': {
      id: '/serene-mind'
      path: '/serene-mind'
      fullPath: '/serene-mind'
      preLoaderRoute: typeof SereneMindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-sfz': {
      id: '/request-sfz'
      path: '/request-sfz'
      fullPath: '/request-sfz'
      preLoaderRoute: typeof RequestSfzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oneness-yoga': {
      id: '/oneness-yoga'
      path: '/oneness-yoga'
      fullPath: '/oneness-yoga'
      preLoaderRoute: typeof OnenessYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allUpcoming-sfz-events': {
      id: '/allUpcoming-sfz-events'
      path: '/allUpcoming-sfz-events'
      fullPath: '/allUpcoming-sfz-events'
      preLoaderRoute: typeof AllUpcomingSfzEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allPast-sfz-events': {
      id: '/allPast-sfz-events'
      path: '/allPast-sfz-events'
      fullPath: '/allPast-sfz-events'
      preLoaderRoute: typeof AllPastSfzEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/submit': {
      id: '/blog/submit'
      path: '/submit'
      fullPath: '/blog/submit'
      preLoaderRoute: typeof BlogSubmitRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/trainers': {
      id: '/admin/trainers'
      path: '/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-media': {
      id: '/admin/site-media'
      path: '/site-media'
      fullPath: '/admin/site-media'
      preLoaderRoute: typeof AdminSiteMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminSiteMediaRoute: typeof AdminSiteMediaRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTrainersRoute: typeof AdminTrainersRoute
  AdminEventsIdRoute: typeof AdminEventsIdRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGalleryRoute: AdminGalleryRoute,
  AdminSiteMediaRoute: AdminSiteMediaRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTrainersRoute: AdminTrainersRoute,
  AdminEventsIdRoute: AdminEventsIdRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
  BlogSubmitRoute: typeof BlogSubmitRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
  BlogSubmitRoute: BlogSubmitRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AllPastSfzEventsRoute: AllPastSfzEventsRoute,
  AllUpcomingSfzEventsRoute: AllUpcomingSfzEventsRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactUsRoute: ContactUsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  LoginRoute: LoginRoute,
  OnenessYogaRoute: OnenessYogaRoute,
  ProgramsRoute: ProgramsRoute,
  RegisterRoute: RegisterRoute,
  RequestSfzRoute: RequestSfzRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SereneMindRoute: SereneMindRoute,
  SfzRoute: SfzRoute,
  SoulSyncRoute: SoulSyncRoute,
  SummerCampRoute: SummerCampRoute,
  WallpapersRoute: WallpapersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
