/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallpapersRouteImport } from './routes/wallpapers'
import { Route as SummerCampRouteImport } from './routes/summer-camp'
import { Route as SoulSyncRouteImport } from './routes/soul-sync'
import { Route as SfzRouteImport } from './routes/sfz'
import { Route as SereneMindRouteImport } from './routes/serene-mind'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestSfzRouteImport } from './routes/request-sfz'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as OnenessYogaRouteImport } from './routes/oneness-yoga'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AllUpcomingSfzEventsRouteImport } from './routes/allUpcoming-sfz-events'
import { Route as AllPastSfzEventsRouteImport } from './routes/allPast-sfz-events'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const WallpapersRoute = WallpapersRouteImport.update({
  id: '/wallpapers',
  path: '/wallpapers',
  getParentRoute: () => rootRouteImport,
} as any)
const SummerCampRoute = SummerCampRouteImport.update({
  id: '/summer-camp',
  path: '/summer-camp',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulSyncRoute = SoulSyncRouteImport.update({
  id: '/soul-sync',
  path: '/soul-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SfzRoute = SfzRouteImport.update({
  id: '/sfz',
  path: '/sfz',
  getParentRoute: () => rootRouteImport,
} as any)
const SereneMindRoute = SereneMindRouteImport.update({
  id: '/serene-mind',
  path: '/serene-mind',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestSfzRoute = RequestSfzRouteImport.update({
  id: '/request-sfz',
  path: '/request-sfz',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OnenessYogaRoute = OnenessYogaRouteImport.update({
  id: '/oneness-yoga',
  path: '/oneness-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AllUpcomingSfzEventsRoute = AllUpcomingSfzEventsRouteImport.update({
  id: '/allUpcoming-sfz-events',
  path: '/allUpcoming-sfz-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AllPastSfzEventsRoute = AllPastSfzEventsRouteImport.update({
  id: '/allPast-sfz-events',
  path: '/allPast-sfz-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/allPast-sfz-events': typeof AllPastSfzEventsRoute
  '/allUpcoming-sfz-events': typeof AllUpcomingSfzEventsRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/oneness-yoga': typeof OnenessYogaRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/request-sfz': typeof RequestSfzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/serene-mind': typeof SereneMindRoute
  '/sfz': typeof SfzRoute
  '/soul-sync': typeof SoulSyncRoute
  '/summer-camp': typeof SummerCampRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/allPast-sfz-events': typeof AllPastSfzEventsRoute
  '/allUpcoming-sfz-events': typeof AllUpcomingSfzEventsRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/oneness-yoga': typeof OnenessYogaRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/request-sfz': typeof RequestSfzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/serene-mind': typeof SereneMindRoute
  '/sfz': typeof SfzRoute
  '/soul-sync': typeof SoulSyncRoute
  '/summer-camp': typeof SummerCampRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/allPast-sfz-events': typeof AllPastSfzEventsRoute
  '/allUpcoming-sfz-events': typeof AllUpcomingSfzEventsRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/oneness-yoga': typeof OnenessYogaRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/request-sfz': typeof RequestSfzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/serene-mind': typeof SereneMindRoute
  '/sfz': typeof SfzRoute
  '/soul-sync': typeof SoulSyncRoute
  '/summer-camp': typeof SummerCampRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/account'
    | '/allPast-sfz-events'
    | '/allUpcoming-sfz-events'
    | '/blog'
    | '/contact-us'
    | '/forgot-password'
    | '/gallery'
    | '/get-involved'
    | '/login'
    | '/oneness-yoga'
    | '/programs'
    | '/register'
    | '/request-sfz'
    | '/reset-password'
    | '/serene-mind'
    | '/sfz'
    | '/soul-sync'
    | '/summer-camp'
    | '/wallpapers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/account'
    | '/allPast-sfz-events'
    | '/allUpcoming-sfz-events'
    | '/blog'
    | '/contact-us'
    | '/forgot-password'
    | '/gallery'
    | '/get-involved'
    | '/login'
    | '/oneness-yoga'
    | '/programs'
    | '/register'
    | '/request-sfz'
    | '/reset-password'
    | '/serene-mind'
    | '/sfz'
    | '/soul-sync'
    | '/summer-camp'
    | '/wallpapers'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/account'
    | '/allPast-sfz-events'
    | '/allUpcoming-sfz-events'
    | '/blog'
    | '/contact-us'
    | '/forgot-password'
    | '/gallery'
    | '/get-involved'
    | '/login'
    | '/oneness-yoga'
    | '/programs'
    | '/register'
    | '/request-sfz'
    | '/reset-password'
    | '/serene-mind'
    | '/sfz'
    | '/soul-sync'
    | '/summer-camp'
    | '/wallpapers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccountRoute: typeof AccountRoute
  AllPastSfzEventsRoute: typeof AllPastSfzEventsRoute
  AllUpcomingSfzEventsRoute: typeof AllUpcomingSfzEventsRoute
  BlogRoute: typeof BlogRoute
  ContactUsRoute: typeof ContactUsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  LoginRoute: typeof LoginRoute
  OnenessYogaRoute: typeof OnenessYogaRoute
  ProgramsRoute: typeof ProgramsRoute
  RegisterRoute: typeof RegisterRoute
  RequestSfzRoute: typeof RequestSfzRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SereneMindRoute: typeof SereneMindRoute
  SfzRoute: typeof SfzRoute
  SoulSyncRoute: typeof SoulSyncRoute
  SummerCampRoute: typeof SummerCampRoute
  WallpapersRoute: typeof WallpapersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallpapers': {
      id: '/wallpapers'
      path: '/wallpapers'
      fullPath: '/wallpapers'
      preLoaderRoute: typeof WallpapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summer-camp': {
      id: '/summer-camp'
      path: '/summer-camp'
      fullPath: '/summer-camp'
      preLoaderRoute: typeof SummerCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul-sync': {
      id: '/soul-sync'
      path: '/soul-sync'
      fullPath: '/soul-sync'
      preLoaderRoute: typeof SoulSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sfz': {
      id: '/sfz'
      path: '/sfz'
      fullPath: '/sfz'
      preLoaderRoute: typeof SfzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serene-mind': {
      id: '/serene-mind'
      path: '/serene-mind'
      fullPath: '/serene-mind'
      preLoaderRoute: typeof SereneMindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-sfz': {
      id: '/request-sfz'
      path: '/request-sfz'
      fullPath: '/request-sfz'
      preLoaderRoute: typeof RequestSfzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oneness-yoga': {
      id: '/oneness-yoga'
      path: '/oneness-yoga'
      fullPath: '/oneness-yoga'
      preLoaderRoute: typeof OnenessYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allUpcoming-sfz-events': {
      id: '/allUpcoming-sfz-events'
      path: '/allUpcoming-sfz-events'
      fullPath: '/allUpcoming-sfz-events'
      preLoaderRoute: typeof AllUpcomingSfzEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allPast-sfz-events': {
      id: '/allPast-sfz-events'
      path: '/allPast-sfz-events'
      fullPath: '/allPast-sfz-events'
      preLoaderRoute: typeof AllPastSfzEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccountRoute: AccountRoute,
  AllPastSfzEventsRoute: AllPastSfzEventsRoute,
  AllUpcomingSfzEventsRoute: AllUpcomingSfzEventsRoute,
  BlogRoute: BlogRoute,
  ContactUsRoute: ContactUsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  LoginRoute: LoginRoute,
  OnenessYogaRoute: OnenessYogaRoute,
  ProgramsRoute: ProgramsRoute,
  RegisterRoute: RegisterRoute,
  RequestSfzRoute: RequestSfzRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SereneMindRoute: SereneMindRoute,
  SfzRoute: SfzRoute,
  SoulSyncRoute: SoulSyncRoute,
  SummerCampRoute: SummerCampRoute,
  WallpapersRoute: WallpapersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
